# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'GTRead' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GTRead
  pod 'Alamofire', '~> 5.2'
  pod 'SnapKit', '~> 5.0.0'
  pod 'ARVideoKit', '~> 1.5.51'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'MJRefresh', '~> 3.5.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'Charts'
  pod 'SwiftEntryKit', '~> 2.0.0'
  pod 'NVActivityIndicatorView'
  pod "Fuse"

  target 'GTReadTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GTReadUITests' do
    # Pods for testing
  end

end
